import Image from "next/image";

const page = () => {
  return (
    <>
      <div
        className="bg-[#282C34] w-full text-white py-8 relative my-20"
        id="about"
      >
        <div className="container mx-auto max-w-7xl px-4 md:px-8">
          <div className="py-8 flex items-center">
            <h2 id="about-me" className="text-3xl font-bold">
              <span className="text-[#C778DE]">#</span>
              about-me
            </h2>
            <hr className="w-1/4 mx-4 border-t border-[#C778DE]" />
            <div className="flex-grow"></div>
          </div>
          <div className="flex flex-col lg:flex-row justify-between gap-8 md:gap-20 lg:gap-40">
            <div className="flex-1 p-4 space-y-8">
              <p className="text-[#ACB2CF]">Hello, i&apos;m Sudip Adhikari!</p>
              <p className="text-[#ACB2CF]">

              As an IT Specialist and Networking Enthusiast with a keen interest in cybersecurity, I'm passionate about leveraging technology to build secure and efficient digital infrastructures.
              </p>
              <p className="text-[#ACB2CF]">
              I specialize in implementing robust networking solutions and optimizing IT systems to meet the evolving needs of businesses. My journey in IT has been driven by a fascination with cybersecurity, constantly seeking to enhance defenses against emerging threats.
              </p>
              <button className="inline-block border border-[#C778DE] py-2 px-4 text-white">
                Read more -&gt;
              </button>
            </div>
            <div className="flex-1 p-4">
              <div className="relative max-w-xs sm:max-w-xs md:max-w-xs lg:max-w-sm xl:max-w-sm mx-auto md:mx-0 md:ml-auto">
                <Image
                  alt="sudip"
                  className="w-auto h-full border-b rounded-xl "
                  src="/laptop.png"
                  width={300}
                  height={300}
                />
                <svg
                  className="w-20 h-20 absolute left-0 top-20"
                  viewBox="0 0 107 108"
                  fill="none"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <circle
                    cx="2.71309"
                    cy="3.31761"
                    r="2.53001"
                    fill="#ABB2BF"
                  ></circle>
                  <circle
                    cx="28.0132"
                    cy="3.31761"
                    r="2.53001"
                    fill="#ABB2BF"
                  ></circle>
                  <circle
                    cx="53.3134"
                    cy="3.31761"
                    r="2.53001"
                    fill="#ABB2BF"
                  ></circle>
                  <circle
                    cx="78.6135"
                    cy="3.31761"
                    r="2.53001"
                    fill="#ABB2BF"
                  ></circle>
                  <circle
                    cx="103.914"
                    cy="3.31761"
                    r="2.53001"
                    fill="#ABB2BF"
                  ></circle>
                  <circle
                    cx="2.71309"
                    cy="28.6177"
                    r="2.53001"
                    fill="#ABB2BF"
                  ></circle>
                  <circle
                    cx="28.0132"
                    cy="28.6174"
                    r="2.53001"
                    fill="#ABB2BF"
                  ></circle>
                  <circle
                    cx="53.3134"
                    cy="28.6174"
                    r="2.53001"
                    fill="#ABB2BF"
                  ></circle>
                  <circle
                    cx="78.6135"
                    cy="28.6174"
                    r="2.53001"
                    fill="#ABB2BF"
                  ></circle>
                  <circle
                    cx="103.914"
                    cy="28.6174"
                    r="2.53001"
                    fill="#ABB2BF"
                  ></circle>
                  <circle
                    cx="2.71309"
                    cy="53.918"
                    r="2.53001"
                    fill="#ABB2BF"
                  ></circle>
                  <circle
                    cx="28.0132"
                    cy="53.9182"
                    r="2.53001"
                    fill="#ABB2BF"
                  ></circle>
                  <circle
                    cx="53.3134"
                    cy="53.9182"
                    r="2.53001"
                    fill="#ABB2BF"
                  ></circle>
                  <circle
                    cx="78.6135"
                    cy="53.9182"
                    r="2.53001"
                    fill="#ABB2BF"
                  ></circle>
                  <circle
                    cx="103.914"
                    cy="53.9182"
                    r="2.53001"
                    fill="#ABB2BF"
                  ></circle>
                  <circle
                    cx="2.71309"
                    cy="79.218"
                    r="2.53001"
                    fill="#ABB2BF"
                  ></circle>
                  <circle
                    cx="28.0132"
                    cy="79.218"
                    r="2.53001"
                    fill="#ABB2BF"
                  ></circle>
                  <circle
                    cx="53.3134"
                    cy="79.218"
                    r="2.53001"
                    fill="#ABB2BF"
                  ></circle>
                  <circle
                    cx="78.6135"
                    cy="79.218"
                    r="2.53001"
                    fill="#ABB2BF"
                  ></circle>
                  <circle
                    cx="103.914"
                    cy="79.218"
                    r="2.53001"
                    fill="#ABB2BF"
                  ></circle>
                  <circle
                    cx="2.71309"
                    cy="104.518"
                    r="2.53001"
                    fill="#ABB2BF"
                  ></circle>
                  <circle
                    cx="28.0132"
                    cy="104.518"
                    r="2.53001"
                    fill="#ABB2BF"
                  ></circle>
                  <circle
                    cx="53.3134"
                    cy="104.518"
                    r="2.53001"
                    fill="#ABB2BF"
                  ></circle>
                  <circle
                    cx="78.6135"
                    cy="104.518"
                    r="2.53001"
                    fill="#ABB2BF"
                  ></circle>
                  <circle
                    cx="103.914"
                    cy="104.518"
                    r="2.53001"
                    fill="#ABB2BF"
                  ></circle>
                </svg>
                <svg
                  className="w-24 h-auto absolute top-1/2 right-20"
                  viewBox="0 0 133 72"
                  fill="none"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <circle
                    cx="3.41289"
                    cy="3.09691"
                    r="2.53001"
                    fill="#ABB2BF"
                  ></circle>
                  <circle
                    cx="35.0381"
                    cy="3.09691"
                    r="2.53001"
                    fill="#ABB2BF"
                  ></circle>
                  <circle
                    cx="66.6633"
                    cy="3.09691"
                    r="2.53001"
                    fill="#ABB2BF"
                  ></circle>
                  <circle
                    cx="98.2884"
                    cy="3.09691"
                    r="2.53001"
                    fill="#ABB2BF"
                  ></circle>
                  <circle
                    cx="129.914"
                    cy="3.09691"
                    r="2.53001"
                    fill="#ABB2BF"
                  ></circle>
                  <circle
                    cx="3.41289"
                    cy="25.0237"
                    r="2.53001"
                    fill="#ABB2BF"
                  ></circle>
                  <circle
                    cx="35.0381"
                    cy="25.0237"
                    r="2.53001"
                    fill="#ABB2BF"
                  ></circle>
                  <circle
                    cx="66.6633"
                    cy="25.0237"
                    r="2.53001"
                    fill="#ABB2BF"
                  ></circle>
                  <circle
                    cx="98.2884"
                    cy="25.0237"
                    r="2.53001"
                    fill="#ABB2BF"
                  ></circle>
                  <circle
                    cx="129.914"
                    cy="25.0237"
                    r="2.53001"
                    fill="#ABB2BF"
                  ></circle>
                  <circle
                    cx="3.41289"
                    cy="46.9505"
                    r="2.53001"
                    fill="#ABB2BF"
                  ></circle>
                  <circle
                    cx="35.0381"
                    cy="46.9505"
                    r="2.53001"
                    fill="#ABB2BF"
                  ></circle>
                  <circle
                    cx="66.6633"
                    cy="46.9505"
                    r="2.53001"
                    fill="#ABB2BF"
                  ></circle>
                  <circle
                    cx="98.2884"
                    cy="46.9505"
                    r="2.53001"
                    fill="#ABB2BF"
                  ></circle>
                  <circle
                    cx="129.914"
                    cy="46.9505"
                    r="2.53001"
                    fill="#ABB2BF"
                  ></circle>
                  <circle
                    cx="3.41289"
                    cy="68.8773"
                    r="2.53001"
                    fill="#ABB2BF"
                  ></circle>
                  <circle
                    cx="35.0381"
                    cy="68.8773"
                    r="2.53001"
                    fill="#ABB2BF"
                  ></circle>
                  <circle
                    cx="66.6633"
                    cy="68.8773"
                    r="2.53001"
                    fill="#ABB2BF"
                  ></circle>
                  <circle
                    cx="98.2884"
                    cy="68.8773"
                    r="2.53001"
                    fill="#ABB2BF"
                  ></circle>
                  <circle
                    cx="129.914"
                    cy="68.8773"
                    r="2.53001"
                    fill="#ABB2BF"
                  ></circle>
                </svg>
              </div>
            </div>
          </div>
          <svg
            className="w-24 h-24 absolute top-2/3 -right-4 hidden 2xl:block"
            viewBox="0 0 107 108"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
          >
            <circle
              cx="2.71309"
              cy="3.31761"
              r="2.53001"
              fill="#ABB2BF"
            ></circle>
            <circle
              cx="28.0132"
              cy="3.31761"
              r="2.53001"
              fill="#ABB2BF"
            ></circle>
            <circle
              cx="53.3134"
              cy="3.31761"
              r="2.53001"
              fill="#ABB2BF"
            ></circle>
            <circle
              cx="78.6135"
              cy="3.31761"
              r="2.53001"
              fill="#ABB2BF"
            ></circle>
            <circle
              cx="103.914"
              cy="3.31761"
              r="2.53001"
              fill="#ABB2BF"
            ></circle>
            <circle
              cx="2.71309"
              cy="28.6177"
              r="2.53001"
              fill="#ABB2BF"
            ></circle>
            <circle
              cx="28.0132"
              cy="28.6174"
              r="2.53001"
              fill="#ABB2BF"
            ></circle>
            <circle
              cx="53.3134"
              cy="28.6174"
              r="2.53001"
              fill="#ABB2BF"
            ></circle>
            <circle
              cx="78.6135"
              cy="28.6174"
              r="2.53001"
              fill="#ABB2BF"
            ></circle>
            <circle
              cx="103.914"
              cy="28.6174"
              r="2.53001"
              fill="#ABB2BF"
            ></circle>
            <circle
              cx="2.71309"
              cy="53.918"
              r="2.53001"
              fill="#ABB2BF"
            ></circle>
            <circle
              cx="28.0132"
              cy="53.9182"
              r="2.53001"
              fill="#ABB2BF"
            ></circle>
            <circle
              cx="53.3134"
              cy="53.9182"
              r="2.53001"
              fill="#ABB2BF"
            ></circle>
            <circle
              cx="78.6135"
              cy="53.9182"
              r="2.53001"
              fill="#ABB2BF"
            ></circle>
            <circle
              cx="103.914"
              cy="53.9182"
              r="2.53001"
              fill="#ABB2BF"
            ></circle>
            <circle
              cx="2.71309"
              cy="79.218"
              r="2.53001"
              fill="#ABB2BF"
            ></circle>
            <circle
              cx="28.0132"
              cy="79.218"
              r="2.53001"
              fill="#ABB2BF"
            ></circle>
            <circle
              cx="53.3134"
              cy="79.218"
              r="2.53001"
              fill="#ABB2BF"
            ></circle>
            <circle
              cx="78.6135"
              cy="79.218"
              r="2.53001"
              fill="#ABB2BF"
            ></circle>
            <circle
              cx="103.914"
              cy="79.218"
              r="2.53001"
              fill="#ABB2BF"
            ></circle>
            <circle
              cx="2.71309"
              cy="104.518"
              r="2.53001"
              fill="#ABB2BF"
            ></circle>
            <circle
              cx="28.0132"
              cy="104.518"
              r="2.53001"
              fill="#ABB2BF"
            ></circle>
            <circle
              cx="53.3134"
              cy="104.518"
              r="2.53001"
              fill="#ABB2BF"
            ></circle>
            <circle
              cx="78.6135"
              cy="104.518"
              r="2.53001"
              fill="#ABB2BF"
            ></circle>
            <circle
              cx="103.914"
              cy="104.518"
              r="2.53001"
              fill="#ABB2BF"
            ></circle>
          </svg>
          <div className="w-40 h-40 hidden 2xl:block border border-[#ACB2CF] absolute -left-20 top-1/3"></div>
        </div>
      </div>
    </>
  );
};

export default page;
